import type { Post } from "./posts";

export const IELTS_POSTS: Post[] = [
  {
    slug: "ielts-band-7-writing-tips",
    date: "2026-10-02",
    readMins: 6,
    cta: "ielts",
    tag: { en: "IELTS", es: "IELTS" },
    en: {
      title: "IELTS Band 7 Writing: 7 tips that actually move your score",
      excerpt: "Stuck at 6 or 6.5 in Writing? These are the changes examiners reward, with a simple plan for Task 1 and Task 2.",
      body: [
        { type: "p", text: `Writing is the part of IELTS where most students get stuck. You can read well, listen well and speak with confidence, and still see 6.0 or 6.5 next to Writing. The good news is that Writing is also the most coachable skill, because examiners mark it against four published criteria. Once you know what they reward, you can practise exactly that.` },
        { type: "h", text: "How Writing is marked" },
        { type: "p", text: `Each task is scored on four criteria that count equally: Task Achievement (Task 1) or Task Response (Task 2), Coherence and Cohesion, Lexical Resource (vocabulary), and Grammatical Range and Accuracy. Task 2 counts for more of your Writing score than Task 1, so it deserves most of your practice time.` },
        { type: "h", text: "7 tips for Band 7" },
        { type: "list", items: [
          `Answer the exact question. Many 6.0 essays are good essays about a slightly different question. Underline every part of the prompt and make sure each part gets a clear answer.`,
          `State your position early and keep it. In opinion essays, say what you think in the introduction and make every body paragraph support it. Changing your mind halfway costs marks.`,
          `One main idea per paragraph. Start with a clear topic sentence, explain it, then give a specific example. Two developed paragraphs beat four thin ones.`,
          `Use linking words naturally, not mechanically. "Furthermore" at the start of every sentence reads as memorised. Vary how you connect ideas, and use referencing words like "this", "such", "these measures".`,
          `Choose precise words over fancy ones. "Reduce traffic congestion" is better than "decrease the amount of cars". Accuracy matters more than rare vocabulary.`,
          `Mix sentence types, and keep them correct. Band 7 needs a range of complex sentences, but frequent errors pull you down. Write sentences you can control.`,
          `Plan for 5 minutes, check for 3. Spend about 40 minutes on Task 2 and 20 on Task 1. A short plan stops you wandering, and a final check catches the small errors that cost a band.`,
        ] },
        { type: "h", text: "Don't forget the word counts" },
        { type: "p", text: `Task 1 needs at least 150 words and Task 2 at least 250. Writing far more doesn't earn extra marks, and it usually adds mistakes. Aim slightly above the minimum and spend the spare time checking.` },
        { type: "h", text: "The fastest way to improve" },
        { type: "p", text: `Practice alone helps, but feedback is what moves the score. Most students repeat the same three or four errors in every essay without noticing. A teacher who marks your writing against the four criteria can show you exactly which ones are holding you below 7, and that is usually where the quickest progress comes from.` },
      ],
    },
    es: {
      title: "IELTS Writing Band 7: 7 consejos que de verdad suben tu nota",
      excerpt: "¿Atascado en 6 o 6.5 en Writing? Estos son los cambios que premian los examinadores, con un plan simple para Task 1 y Task 2.",
      body: [
        { type: "p", text: `Writing es la parte del IELTS donde más estudiantes se quedan atascados. Puedes leer bien, escuchar bien y hablar con confianza, y aun así ver 6.0 o 6.5 en Writing. La buena noticia es que Writing es también la habilidad que más se puede entrenar, porque los examinadores califican con cuatro criterios públicos. Cuando sabes qué premian, puedes practicar exactamente eso.` },
        { type: "h", text: "Cómo se califica Writing" },
        { type: "p", text: `Cada tarea se califica con cuatro criterios que valen lo mismo: Task Achievement (Task 1) o Task Response (Task 2), Coherence and Cohesion, Lexical Resource (vocabulario) y Grammatical Range and Accuracy. Task 2 pesa más en tu nota de Writing que Task 1, así que merece la mayor parte de tu práctica.` },
        { type: "h", text: "7 consejos para Band 7" },
        { type: "list", items: [
          `Responde exactamente la pregunta. Muchos ensayos de 6.0 son buenos ensayos sobre una pregunta un poco distinta. Subraya cada parte de la consigna y asegúrate de responder cada una con claridad.`,
          `Di tu postura pronto y mantenla. En los ensayos de opinión, di lo que piensas en la introducción y haz que cada párrafo la apoye. Cambiar de opinión a la mitad cuesta puntos.`,
          `Una idea principal por párrafo. Empieza con una frase temática clara, explícala y da un ejemplo concreto. Dos párrafos desarrollados valen más que cuatro superficiales.`,
          `Usa conectores con naturalidad, no de forma mecánica. "Furthermore" al inicio de cada frase suena memorizado. Varía cómo conectas las ideas y usa palabras de referencia como "this", "such", "these measures".`,
          `Elige palabras precisas, no rebuscadas. "Reduce traffic congestion" es mejor que "decrease the amount of cars". La precisión importa más que el vocabulario raro.`,
          `Combina tipos de frases y mantenlas correctas. Band 7 necesita variedad de frases complejas, pero los errores frecuentes te bajan la nota. Escribe frases que puedas controlar.`,
          `Planifica 5 minutos y revisa 3. Dedica unos 40 minutos a Task 2 y 20 a Task 1. Un plan corto evita que te desvíes, y una revisión final atrapa los pequeños errores que cuestan una banda.`,
        ] },
        { type: "h", text: "No olvides el número de palabras" },
        { type: "p", text: `Task 1 necesita al menos 150 palabras y Task 2 al menos 250. Escribir mucho más no da puntos extra y normalmente añade errores. Apunta un poco por encima del mínimo y usa el tiempo sobrante para revisar.` },
        { type: "h", text: "La forma más rápida de mejorar" },
        { type: "p", text: `Practicar solo ayuda, pero lo que mueve la nota es la retroalimentación. La mayoría de los estudiantes repite los mismos tres o cuatro errores en cada ensayo sin darse cuenta. Un profesor que corrige tu escritura con los cuatro criterios puede mostrarte exactamente cuáles te mantienen por debajo de 7, y ahí suele estar el progreso más rápido.` },
      ],
    },
  },
  {
    slug: "ielts-vs-pte-which-is-easier",
    date: "2026-10-02",
    readMins: 5,
    cta: "ielts",
    tag: { en: "IELTS", es: "IELTS" },
    en: {
      title: "IELTS vs PTE: which is easier for you?",
      excerpt: "Neither test is easier for everyone. Here's how they differ, and how to choose the one that suits the way you work.",
      body: [
        { type: "p", text: `"Which one is easier?" is the question we hear most from students choosing between IELTS and PTE Academic. The honest answer: neither is easier for everyone. They test the same skills in very different ways, so the right choice depends on how you work best.` },
        { type: "h", text: "First, check what you're allowed to take" },
        { type: "p", text: `Before comparing difficulty, check exactly which tests your university, employer or visa accepts, and which version (for example IELTS Academic or General Training). Requirements change, so always confirm on the official website of the organisation you're applying to.` },
        { type: "h", text: "The main differences" },
        { type: "list", items: [
          `Speaking: in IELTS you talk face to face with a human examiner for about 11 to 14 minutes. In PTE you speak into a microphone and a computer scores you.`,
          `Scoring: IELTS is marked by trained examiners for Writing and Speaking. PTE is scored automatically, which rewards clear, steady delivery and following the task format closely.`,
          `Format: PTE is fully computer-based with many short, fast tasks. IELTS has fewer, longer tasks, and you can take it on paper or on computer.`,
          `Results: PTE results usually come back within a few days. Computer-delivered IELTS is also fast, while paper-based IELTS takes longer.`,
        ] },
        { type: "h", text: "IELTS may suit you if…" },
        { type: "list", items: [
          `You speak more naturally with a real person than with a microphone.`,
          `You like having time to read and think through longer texts.`,
          `You're comfortable writing structured essays.`,
        ] },
        { type: "h", text: "PTE may suit you if…" },
        { type: "list", items: [
          `You're comfortable on a computer and with fast, timed tasks.`,
          `Speaking to an examiner makes you nervous.`,
          `You need results quickly.`,
        ] },
        { type: "h", text: "Our advice" },
        { type: "p", text: `Take a short practice test in both formats before you book. Whichever one feels more natural is usually the one you'll score higher in. And whichever you choose, the biggest gains come from learning that test's specific task types and timing, not just general English.` },
      ],
    },
    es: {
      title: "IELTS vs PTE: ¿cuál es más fácil para ti?",
      excerpt: "Ningún examen es más fácil para todos. Así se diferencian, y así eliges el que mejor encaja con tu forma de trabajar.",
      body: [
        { type: "p", text: `"¿Cuál es más fácil?" es la pregunta que más escuchamos de estudiantes que dudan entre IELTS y PTE Academic. La respuesta honesta: ninguno es más fácil para todos. Evalúan las mismas habilidades de formas muy distintas, así que la mejor opción depende de cómo trabajas mejor.` },
        { type: "h", text: "Primero, revisa qué examen te aceptan" },
        { type: "p", text: `Antes de comparar la dificultad, confirma exactamente qué exámenes acepta tu universidad, empleador o visa, y qué versión (por ejemplo IELTS Academic o General Training). Los requisitos cambian, así que verifica siempre en la web oficial de la organización a la que aplicas.` },
        { type: "h", text: "Las diferencias principales" },
        { type: "list", items: [
          `Speaking: en IELTS hablas cara a cara con un examinador durante unos 11 a 14 minutos. En PTE hablas a un micrófono y te califica una computadora.`,
          `Calificación: en IELTS, Writing y Speaking los califican examinadores capacitados. PTE se califica automáticamente, lo que premia una expresión clara y constante y seguir el formato de cada tarea.`,
          `Formato: PTE es totalmente por computadora, con muchas tareas cortas y rápidas. IELTS tiene menos tareas pero más largas, y puedes hacerlo en papel o en computadora.`,
          `Resultados: los resultados de PTE suelen llegar en pocos días. El IELTS por computadora también es rápido; el IELTS en papel tarda más.`,
        ] },
        { type: "h", text: "IELTS puede ser para ti si…" },
        { type: "list", items: [
          `Hablas con más naturalidad con una persona que con un micrófono.`,
          `Te gusta tener tiempo para leer y pensar textos largos.`,
          `Te sientes cómodo escribiendo ensayos estructurados.`,
        ] },
        { type: "h", text: "PTE puede ser para ti si…" },
        { type: "list", items: [
          `Te sientes cómodo con la computadora y con tareas rápidas y cronometradas.`,
          `Hablar con un examinador te pone nervioso.`,
          `Necesitas resultados rápido.`,
        ] },
        { type: "h", text: "Nuestro consejo" },
        { type: "p", text: `Haz un examen de práctica corto en ambos formatos antes de reservar. El que te resulte más natural suele ser en el que sacas más puntos. Y elijas el que elijas, los mayores avances vienen de aprender los tipos de tarea y los tiempos de ese examen, no solo inglés general.` },
      ],
    },
  },
  {
    slug: "ielts-band-6-to-7-how-long",
    date: "2026-10-02",
    readMins: 5,
    cta: "ielts",
    tag: { en: "IELTS", es: "IELTS" },
    en: {
      title: "How long does it take to go from IELTS Band 6 to 7?",
      excerpt: "It depends on where your points are lost. Here's a realistic way to estimate your timeline, and how to shorten it.",
      body: [
        { type: "p", text: `It's one of the most common goals in IELTS: you have a 6, and you need a 7 for your visa, your nursing registration or your university. So how long will it take? The honest answer is "it depends", but it depends on things you can measure.` },
        { type: "h", text: "Why there's no single answer" },
        { type: "p", text: `Your overall band is the average of four skills. Someone with 6.0 overall might have 7.0 in Reading and 5.5 in Writing. Someone else might be 6.0 in everything. The first person mostly needs to fix one skill; the second needs to lift all four. Their timelines can be very different.` },
        { type: "h", text: "A rough rule of thumb" },
        { type: "p", text: `Moving up a full level of general English usually takes a few hundred hours of study. But going from 6 to 7 in IELTS is often faster than that, because many students already have the English and are losing marks to exam technique: not answering the question exactly, running out of time, or repeating the same grammar errors.` },
        { type: "list", items: [
          `Already 6.5 in most skills, with one weak skill: often around 1 to 2 months of focused practice on that skill.`,
          `A solid 6.0 across the board: often around 2 to 4 months of regular practice.`,
          `Below 6.0 in two or more skills: plan for longer, and build general English alongside exam practice.`,
        ] },
        { type: "p", text: `These are typical ranges, not promises. How often you study and how much feedback you get make the biggest difference.` },
        { type: "h", text: "How to shorten your timeline" },
        { type: "list", items: [
          `Find out your band in each skill, not just your overall score. You can't fix what you haven't measured.`,
          `Put most of your time into your weakest skill. That's usually Writing or Speaking.`,
          `Get feedback on your writing and speaking. Practice without correction tends to repeat the same mistakes.`,
          `Do timed practice tests regularly, so the real exam feels familiar.`,
          `Study a little every day rather than a lot once a week.`,
        ] },
        { type: "h", text: "Start with an honest starting point" },
        { type: "p", text: `The quickest way to know your timeline is to know exactly where you are now. Take our free band check, then get your exact band in each skill from a teacher in a free demo lesson. With that, you can plan backwards from your exam date with real numbers.` },
      ],
    },
    es: {
      title: "¿Cuánto tiempo se tarda en pasar de IELTS Band 6 a 7?",
      excerpt: "Depende de dónde pierdes puntos. Así puedes estimar tu tiempo de forma realista, y cómo acortarlo.",
      body: [
        { type: "p", text: `Es una de las metas más comunes en IELTS: tienes un 6 y necesitas un 7 para tu visa, tu registro de enfermería o tu universidad. ¿Cuánto tiempo te llevará? La respuesta honesta es "depende", pero depende de cosas que puedes medir.` },
        { type: "h", text: "Por qué no hay una sola respuesta" },
        { type: "p", text: `Tu banda general es el promedio de cuatro habilidades. Alguien con 6.0 general puede tener 7.0 en Reading y 5.5 en Writing. Otra persona puede tener 6.0 en todo. La primera necesita sobre todo arreglar una habilidad; la segunda necesita subir las cuatro. Sus tiempos pueden ser muy distintos.` },
        { type: "h", text: "Una regla aproximada" },
        { type: "p", text: `Subir un nivel completo de inglés general suele llevar unos cientos de horas de estudio. Pero pasar de 6 a 7 en IELTS a menudo es más rápido, porque muchos estudiantes ya tienen el inglés y pierden puntos por técnica de examen: no responder exactamente la pregunta, quedarse sin tiempo o repetir los mismos errores de gramática.` },
        { type: "list", items: [
          `Ya tienes 6.5 en casi todo y una habilidad débil: a menudo entre 1 y 2 meses de práctica enfocada en esa habilidad.`,
          `Un 6.0 sólido en todo: a menudo entre 2 y 4 meses de práctica regular.`,
          `Menos de 6.0 en dos o más habilidades: planifica más tiempo y trabaja el inglés general junto con la práctica de examen.`,
        ] },
        { type: "p", text: `Son rangos típicos, no promesas. La frecuencia con la que estudias y cuánta retroalimentación recibes marcan la mayor diferencia.` },
        { type: "h", text: "Cómo acortar tu tiempo" },
        { type: "list", items: [
          `Conoce tu banda en cada habilidad, no solo la general. No puedes arreglar lo que no has medido.`,
          `Dedica la mayor parte del tiempo a tu habilidad más débil. Normalmente es Writing o Speaking.`,
          `Recibe correcciones de tu escritura y tu expresión oral. Practicar sin corrección suele repetir los mismos errores.`,
          `Haz exámenes de práctica cronometrados con regularidad, para que el examen real te resulte familiar.`,
          `Estudia un poco cada día en lugar de mucho una vez por semana.`,
        ] },
        { type: "h", text: "Empieza con un punto de partida honesto" },
        { type: "p", text: `La forma más rápida de conocer tu tiempo es saber exactamente dónde estás ahora. Haz nuestro band check gratis y luego recibe tu banda exacta en cada habilidad con un profesor en una clase de prueba gratis. Con eso puedes planificar hacia atrás desde la fecha de tu examen con números reales.` },
      ],
    },
  },
];
