// MundoLingu Terms & Conditions (EN · ES · AR).
// To update: edit the text below and change `updated`.

export type TermsLang = "en" | "es" | "ar";

type Section = {
  h: string;
  p?: string[];
  bullets?: string[];
  box?: { title: string; items: { b: string; t: string }[] };
  after?: string[];
};

type Terms = { title: string; sub: string; updated: string; intro: string; sections: Section[]; thanks: string; back: string; contents: string };

export const TERMS: Record<TermsLang, Terms> = {
  en: {
    title: "Terms & Conditions",
    sub: "MundoLingu — Online Language School",
    updated: "Last updated: 26 August 2026",
    back: "Back to home",
    contents: "Contents",
    intro: "Welcome to MundoLingu. These Terms & Conditions (the “Terms”) explain how our online language lessons and memberships work, and the rules that apply when you book, pay for, and take part in our classes. MundoLingu is an online language school operated from Dubai, United Arab Emirates, offering English lessons for Spanish speakers and Spanish lessons for English speakers. By booking a lesson, creating an account, or purchasing a membership or lesson package, you agree to these Terms. Please read them carefully.",
    sections: [
      { h: "1. The services we provide",
        p: ["MundoLingu provides online language education, which may include:"],
        bullets: [
          "One-to-one (private) language lessons with a MundoLingu teacher.",
          "Live group speaking classes held on scheduled evenings each week.",
          "A monthly membership giving access to a members’ area with video lessons, live classes, an events calendar, and a library of downloadable workbooks.",
          "Learning materials such as workbooks, worksheets, and practice resources.",
          "A free demo lesson for new students who want to try MundoLingu before enrolling.",
        ],
        after: ["The exact lessons, materials, and features available may change over time as we improve our service. We’ll always aim to give you what was described when you enrolled."] },
      { h: "2. Your account and eligibility",
        bullets: [
          "Our lessons and memberships are intended for adults (18 years or older). A student under 18 may take part only with the consent and supervision of a parent or legal guardian, who accepts these Terms on the student’s behalf.",
          "You are responsible for keeping your account details and any access code or login secure, and for all activity that takes place under your account.",
          "Please give us accurate information when you sign up (for example your name, email, and contact number) so we can deliver your lessons and reach you if needed.",
        ] },
      { h: "3. Bookings, packages and payment",
        bullets: [
          "Lessons and packages are booked in advance and paid for before the lesson or period begins, using the payment method shown to you or agreed with us (for example, bank transfer confirmed via WhatsApp).",
          "A “package” is a set of lessons purchased together (for example a block of private lessons or a term of group classes). A “membership period” is the month you have paid for.",
          "Prices are shown at the time of purchase. We may update our prices from time to time, but a change will never affect a package or membership period you have already paid for.",
          "Lesson times are reserved specifically for you. When you book a time slot, that slot is held for you and your teacher, which is why the cancellation rules in Section 4 apply.",
        ] },
      { h: "4. Cancellations, rescheduling and missed lessons",
        p: ["We know life happens, and we’ll always try to be flexible. To keep scheduling fair for our teachers and other students, the following applies to any lesson that has a reserved time slot (private lessons and live group classes):"],
        box: { title: "How lesson cancellations work", items: [
          { b: "More than 24 hours’ notice.", t: "You may reschedule or cancel free of charge, and the lesson stays in your package to be used another time." },
          { b: "Less than 24 hours’ notice, or not showing up, without a valid reason.", t: "The lesson is counted as completed and deducted from your package. A valid reason includes things such as illness, a family emergency, or another genuine situation beyond your control — assessed reasonably and in good faith." },
          { b: "Fair-use allowance.", t: "Each student may use this late-cancellation allowance up to two (2) times within a single package or membership period." },
          { b: "After the second time.", t: "If it happens a third time, we’ll pause and have a friendly conversation with you to understand what’s going on and find a solution that works — whether that’s adjusting your schedule, your plan, or the support we give you. Our goal is always to help you keep learning, never to penalise you." },
        ] },
        after: ["Whenever possible, please give us as much notice as you can so we can offer your slot to another student and help you find a better time. If you need to cancel, let us know by your usual contact channel (for example WhatsApp or email)."] },
      { h: "5. Free demo lesson",
        p: ["New students may book one free demo lesson so we can get to know each other and plan the right learning path for you. The demo lesson is free of charge and carries no obligation to continue. It’s offered per student, and we may limit repeat demo bookings."] },
      { h: "6. Membership",
        bullets: [
          "Membership is billed monthly and renews automatically until you cancel.",
          "You can cancel your membership at any time. When you cancel, you’ll keep access until the end of the period you’ve already paid for, and you won’t be charged again after that.",
          "Introductory or promotional pricing (for example a reduced first month) applies only as described at the time you sign up; standard pricing applies afterwards.",
          "Membership gives you access to the members’ area and its content as it stands from time to time. We add new materials regularly, but the specific content available may change.",
        ] },
      { h: "7. Refunds",
        p: ["Because our lessons, materials, and members’ content are delivered digitally, and because lesson slots are reserved specifically for you, fees are generally non-refundable except where a refund is required by law. Lessons that have already been taken or counted as completed (including under Section 4) are not refundable. If you believe there are exceptional circumstances, please contact us — we’ll always review your situation fairly and in good faith."] },
      { h: "8. Student conduct and community",
        p: ["MundoLingu is a friendly, respectful learning community. When taking part in lessons, live classes, or any MundoLingu space, you agree to:"],
        bullets: [
          "Treat teachers and fellow students with courtesy and respect.",
          "Not record, share, or republish lessons, live classes, or other students’ contributions without permission.",
          "Not use MundoLingu’s services for any unlawful, harmful, or abusive purpose.",
        ],
        after: ["We may pause or end access for anyone who behaves abusively or repeatedly breaks these Terms, where appropriate without a refund."] },
      { h: "9. Learning materials and intellectual property",
        p: ["All MundoLingu lessons, workbooks, videos, graphics, and other materials are the property of MundoLingu (or used with permission) and are protected by intellectual property laws. They are provided for your own personal learning only. You may download and use materials for your studies, but you may not copy, resell, distribute, or share them publicly without our written permission."] },
      { h: "10. Privacy and your data",
        p: ["We collect and use personal information (such as your name, email, phone number, and learning preferences) only to provide and improve our services, arrange your lessons, and communicate with you. We do not sell your personal data. If you would like to know what information we hold, or ask us to update or delete it, please contact us using the details at the end of these Terms."] },
      { h: "11. Availability of the service",
        p: ["We work hard to keep lessons and the members’ area running smoothly, but online services can occasionally be affected by technical issues, third-party platforms, or events outside our control. If a lesson can’t go ahead because of a problem on our side, we’ll reschedule it or return it to your package."] },
      { h: "12. Changes to these Terms",
        p: ["We may update these Terms from time to time — for example, to reflect new features or legal requirements. The latest version will always be published on our website with an updated date. If you keep using our services after a change, that means you accept the updated Terms."] },
      { h: "13. Liability",
        p: ["MundoLingu provides language education and support to help you learn, but we can’t guarantee any specific result, exam score, or level of fluency, as progress depends on many factors including your own practice. To the fullest extent permitted by law, MundoLingu is not liable for indirect or unforeseeable losses arising from the use of our services. Nothing in these Terms limits any rights you may have that cannot be excluded by law."] },
      { h: "14. Governing law",
        p: ["These Terms are governed by the laws of the United Arab Emirates (Dubai), without affecting any mandatory consumer-protection rights you may have in your own country of residence."] },
      { h: "15. Contact us",
        p: ["If you have any questions about these Terms or your lessons, we’re happy to help:"],
        bullets: ["Email: mundolingu@gmail.com", "WhatsApp: +971 50 429 6090", "Website: www.mundolingu.com", "Instagram: @mundolingu"] },
    ],
    thanks: "Thank you for learning with MundoLingu. We’re looking forward to helping you reach your language goals.",
  },

  es: {
    title: "Términos y Condiciones",
    sub: "MundoLingu — Escuela de Idiomas en Línea",
    updated: "Última actualización: 26 de agosto de 2026",
    back: "Volver al inicio",
    contents: "Contenido",
    intro: "Te damos la bienvenida a MundoLingu. Estos Términos y Condiciones (los «Términos») explican cómo funcionan nuestras clases y membresías de idiomas en línea, y las reglas que se aplican cuando reservas, pagas y participas en nuestras clases. MundoLingu es una escuela de idiomas en línea gestionada desde Dubái, Emiratos Árabes Unidos, que ofrece clases de inglés para hispanohablantes y clases de español para angloparlantes. Al reservar una clase, crear una cuenta o adquirir una membresía o paquete de clases, aceptas estos Términos. Por favor, léelos con atención.",
    sections: [
      { h: "1. Los servicios que ofrecemos",
        p: ["MundoLingu ofrece educación de idiomas en línea, que puede incluir:"],
        bullets: [
          "Clases particulares (uno a uno) con un profesor de MundoLingu.",
          "Clases grupales de conversación en vivo, en horarios establecidos por las tardes cada semana.",
          "Una membresía mensual que da acceso a un área de miembros con lecciones en video, clases en vivo, un calendario de eventos y una biblioteca de cuadernos de trabajo descargables.",
          "Materiales de aprendizaje como cuadernos de trabajo, hojas de ejercicios y recursos de práctica.",
          "Una clase de prueba gratuita para nuevos estudiantes que quieran conocer MundoLingu antes de inscribirse.",
        ],
        after: ["Las clases, los materiales y las funciones disponibles pueden cambiar con el tiempo a medida que mejoramos nuestro servicio. Siempre procuraremos ofrecerte lo que se describió cuando te inscribiste."] },
      { h: "2. Tu cuenta y requisitos",
        bullets: [
          "Nuestras clases y membresías están dirigidas a personas adultas (mayores de 18 años). Un estudiante menor de 18 años solo puede participar con el consentimiento y la supervisión de un padre, madre o tutor legal, quien acepta estos Términos en su nombre.",
          "Eres responsable de mantener seguros los datos de tu cuenta y cualquier código de acceso o contraseña, así como de toda la actividad que se realice en tu cuenta.",
          "Por favor, proporciónanos información correcta al registrarte (por ejemplo, tu nombre, correo electrónico y número de contacto) para que podamos impartir tus clases y comunicarnos contigo si es necesario.",
        ] },
      { h: "3. Reservas, paquetes y pagos",
        bullets: [
          "Las clases y los paquetes se reservan por adelantado y se pagan antes de que comience la clase o el periodo, mediante el método de pago que se te indique o que acordemos contigo (por ejemplo, transferencia bancaria confirmada por WhatsApp).",
          "Un «paquete» es un conjunto de clases adquiridas juntas (por ejemplo, un bloque de clases particulares o un periodo de clases grupales). Un «periodo de membresía» es el mes que has pagado.",
          "Los precios se muestran en el momento de la compra. Podemos actualizar nuestros precios ocasionalmente, pero ningún cambio afectará a un paquete o periodo de membresía que ya hayas pagado.",
          "Los horarios de clase se reservan específicamente para ti. Cuando reservas un horario, ese espacio queda apartado para ti y tu profesor, y por eso se aplican las reglas de cancelación de la Sección 4.",
        ] },
      { h: "4. Cancelaciones, cambios de horario y clases perdidas",
        p: ["Sabemos que la vida pasa, y siempre intentaremos ser flexibles. Para que la organización de horarios sea justa para nuestros profesores y demás estudiantes, lo siguiente se aplica a cualquier clase que tenga un horario reservado (clases particulares y clases grupales en vivo):"],
        box: { title: "Cómo funcionan las cancelaciones de clases", items: [
          { b: "Con más de 24 horas de antelación.", t: "Puedes cambiar el horario o cancelar sin costo, y la clase permanece en tu paquete para usarla en otro momento." },
          { b: "Con menos de 24 horas de antelación, o si no te presentas, sin un motivo válido.", t: "La clase se cuenta como realizada y se descuenta de tu paquete. Un motivo válido incluye situaciones como enfermedad, una emergencia familiar u otra circunstancia genuina fuera de tu control, evaluada de forma razonable y de buena fe." },
          { b: "Margen de uso razonable.", t: "Cada estudiante puede usar este margen de cancelación de último momento hasta dos (2) veces dentro de un mismo paquete o periodo de membresía." },
          { b: "Después de la segunda vez.", t: "Si ocurre una tercera vez, haremos una pausa y tendremos una conversación amistosa contigo para entender qué está pasando y encontrar una solución que funcione, ya sea ajustar tu horario, tu plan o el apoyo que te damos. Nuestro objetivo siempre es ayudarte a seguir aprendiendo, nunca penalizarte." },
        ] },
        after: ["Siempre que sea posible, avísanos con la mayor antelación que puedas para que podamos ofrecer tu horario a otro estudiante y ayudarte a encontrar un mejor momento. Si necesitas cancelar, avísanos por tu canal de contacto habitual (por ejemplo, WhatsApp o correo electrónico)."] },
      { h: "5. Clase de prueba gratuita",
        p: ["Los nuevos estudiantes pueden reservar una clase de prueba gratuita para conocernos y planificar juntos el mejor camino de aprendizaje para ti. La clase de prueba es gratuita y no implica ninguna obligación de continuar. Se ofrece por estudiante, y podemos limitar la repetición de clases de prueba."] },
      { h: "6. Membresía",
        bullets: [
          "La membresía se cobra mensualmente y se renueva automáticamente hasta que la canceles.",
          "Puedes cancelar tu membresía en cualquier momento. Al cancelar, conservarás el acceso hasta el final del periodo que ya hayas pagado, y no se te volverá a cobrar después de eso.",
          "Los precios promocionales o de introducción (por ejemplo, un primer mes con descuento) se aplican únicamente como se describe en el momento de tu registro; después se aplica el precio estándar.",
          "La membresía te da acceso al área de miembros y a su contenido tal como esté disponible en cada momento. Agregamos materiales nuevos con regularidad, pero el contenido específico disponible puede cambiar.",
        ] },
      { h: "7. Reembolsos",
        p: ["Debido a que nuestras clases, materiales y contenido para miembros se entregan de forma digital, y a que los horarios de clase se reservan específicamente para ti, las tarifas por lo general no son reembolsables, salvo cuando la ley exija un reembolso. Las clases que ya se hayan tomado o contado como realizadas (incluidas las de la Sección 4) no son reembolsables. Si consideras que existen circunstancias excepcionales, contáctanos: siempre revisaremos tu situación de forma justa y de buena fe."] },
      { h: "8. Conducta del estudiante y comunidad",
        p: ["MundoLingu es una comunidad de aprendizaje amable y respetuosa. Al participar en las clases, las clases en vivo o cualquier espacio de MundoLingu, aceptas:"],
        bullets: [
          "Tratar a los profesores y a los demás estudiantes con cortesía y respeto.",
          "No grabar, compartir ni volver a publicar las clases, las clases en vivo o las aportaciones de otros estudiantes sin autorización.",
          "No usar los servicios de MundoLingu para ningún fin ilícito, dañino o abusivo.",
        ],
        after: ["Podemos suspender o cancelar el acceso de cualquier persona que se comporte de forma abusiva o incumpla estos Términos de forma reiterada, sin reembolso cuando corresponda."] },
      { h: "9. Materiales de aprendizaje y propiedad intelectual",
        p: ["Todas las clases, cuadernos de trabajo, videos, gráficos y demás materiales de MundoLingu son propiedad de MundoLingu (o se utilizan con autorización) y están protegidos por las leyes de propiedad intelectual. Se proporcionan únicamente para tu aprendizaje personal. Puedes descargar y usar los materiales para tus estudios, pero no puedes copiarlos, revenderlos, distribuirlos ni compartirlos públicamente sin nuestra autorización por escrito."] },
      { h: "10. Privacidad y tus datos",
        p: ["Recopilamos y usamos datos personales (como tu nombre, correo electrónico, número de teléfono y preferencias de aprendizaje) únicamente para prestar y mejorar nuestros servicios, organizar tus clases y comunicarnos contigo. No vendemos tus datos personales. Si deseas saber qué información tenemos sobre ti, o pedirnos que la actualicemos o eliminemos, contáctanos usando los datos que aparecen al final de estos Términos."] },
      { h: "11. Disponibilidad del servicio",
        p: ["Nos esforzamos por mantener las clases y el área de miembros funcionando sin problemas, pero los servicios en línea pueden verse afectados ocasionalmente por problemas técnicos, plataformas de terceros o situaciones fuera de nuestro control. Si una clase no puede realizarse por un problema de nuestra parte, la reprogramaremos o la devolveremos a tu paquete."] },
      { h: "12. Cambios en estos Términos",
        p: ["Podemos actualizar estos Términos ocasionalmente, por ejemplo, para reflejar nuevas funciones o requisitos legales. La versión más reciente siempre estará publicada en nuestro sitio web con la fecha actualizada. Si sigues usando nuestros servicios después de un cambio, significa que aceptas los Términos actualizados."] },
      { h: "13. Responsabilidad",
        p: ["MundoLingu ofrece educación y apoyo en idiomas para ayudarte a aprender, pero no podemos garantizar ningún resultado específico, calificación de examen ni nivel de fluidez, ya que el progreso depende de muchos factores, incluida tu propia práctica. En la medida máxima permitida por la ley, MundoLingu no se hace responsable de pérdidas indirectas o imprevisibles derivadas del uso de nuestros servicios. Nada en estos Términos limita los derechos que puedas tener y que no puedan excluirse por ley."] },
      { h: "14. Legislación aplicable",
        p: ["Estos Términos se rigen por las leyes de los Emiratos Árabes Unidos (Dubái), sin que ello afecte los derechos obligatorios de protección al consumidor que puedas tener en tu país de residencia."] },
      { h: "15. Contáctanos",
        p: ["Si tienes alguna pregunta sobre estos Términos o tus clases, con gusto te ayudamos:"],
        bullets: ["Correo electrónico: mundolingu@gmail.com", "WhatsApp: +971 50 429 6090", "Sitio web: www.mundolingu.com", "Instagram: @mundolingu"] },
    ],
    thanks: "Gracias por aprender con MundoLingu. Tenemos muchas ganas de ayudarte a alcanzar tus metas con los idiomas.",
  },

  ar: {
    title: "الشروط والأحكام",
    sub: "MundoLingu — مدرسة لغات عبر الإنترنت",
    updated: "آخر تحديث: 26 أغسطس 2026",
    back: "العودة إلى الصفحة الرئيسية",
    contents: "المحتويات",
    intro: "مرحبًا بك في MundoLingu. توضّح هذه الشروط والأحكام («الشروط») كيفية عمل دروس اللغات والعضويات التي نقدّمها عبر الإنترنت، والقواعد التي تنطبق عند حجز دروسنا والدفع مقابلها والمشاركة فيها. MundoLingu مدرسة لغات عبر الإنترنت تُدار من دبي، الإمارات العربية المتحدة، وتقدّم دروسًا في اللغة الإنجليزية للناطقين بالإسبانية ودروسًا في اللغة الإسبانية للناطقين بالإنجليزية. بحجزك درسًا أو إنشائك حسابًا أو شرائك عضوية أو باقة دروس، فإنك توافق على هذه الشروط. يرجى قراءتها بعناية.",
    sections: [
      { h: "1. الخدمات التي نقدّمها",
        p: ["تقدّم MundoLingu تعليمًا للغات عبر الإنترنت، وقد يشمل ذلك:"],
        bullets: [
          "دروسًا فردية (خاصة) في اللغة مع معلم من MundoLingu.",
          "حصص محادثة جماعية مباشرة تُعقد في أمسيات محددة كل أسبوع.",
          "عضوية شهرية تتيح الوصول إلى منطقة الأعضاء التي تضم دروس فيديو وحصصًا مباشرة وتقويمًا للفعاليات ومكتبة من كتب التمارين القابلة للتنزيل.",
          "مواد تعليمية مثل كتب التمارين وأوراق العمل وموارد التدريب.",
          "درسًا تجريبيًا مجانيًا للطلاب الجدد الذين يرغبون في تجربة MundoLingu قبل التسجيل.",
        ],
        after: ["قد تتغير الدروس والمواد والميزات المتاحة بمرور الوقت مع تحسيننا لخدمتنا. وسنسعى دائمًا إلى تقديم ما وُصف لك عند تسجيلك."] },
      { h: "2. حسابك وشروط الأهلية",
        bullets: [
          "دروسنا وعضوياتنا مخصصة للبالغين (18 عامًا فأكثر). لا يجوز للطالب الذي يقل عمره عن 18 عامًا المشاركة إلا بموافقة وإشراف أحد الوالدين أو الوصي القانوني، الذي يقبل هذه الشروط نيابةً عن الطالب.",
          "أنت مسؤول عن الحفاظ على أمان بيانات حسابك وأي رمز دخول أو بيانات تسجيل دخول، وعن جميع الأنشطة التي تتم من خلال حسابك.",
          "يرجى تزويدنا بمعلومات دقيقة عند التسجيل (مثل اسمك وبريدك الإلكتروني ورقم التواصل) حتى نتمكن من تقديم دروسك والتواصل معك عند الحاجة.",
        ] },
      { h: "3. الحجوزات والباقات والدفع",
        bullets: [
          "تُحجز الدروس والباقات مسبقًا ويُدفع مقابلها قبل بدء الدرس أو الفترة، باستخدام طريقة الدفع المعروضة عليك أو المتفق عليها معنا (مثل التحويل البنكي المؤكَّد عبر واتساب).",
          "«الباقة» هي مجموعة من الدروس تُشترى معًا (مثل مجموعة من الدروس الخاصة أو فصل من الحصص الجماعية). و«فترة العضوية» هي الشهر الذي دفعت مقابله.",
          "تُعرض الأسعار وقت الشراء. وقد نحدّث أسعارنا من وقت لآخر، لكن أي تغيير لن يؤثر أبدًا على باقة أو فترة عضوية دفعت مقابلها بالفعل.",
          "مواعيد الدروس محجوزة لك خصيصًا. عندما تحجز موعدًا، يُخصَّص هذا الموعد لك ولمعلمك، ولهذا تنطبق قواعد الإلغاء الواردة في البند 4.",
        ] },
      { h: "4. الإلغاء وتغيير المواعيد والدروس الفائتة",
        p: ["نعلم أن الظروف تتغير، وسنحاول دائمًا أن نكون مرنين. ولضمان عدالة الجدولة لمعلمينا ولبقية الطلاب، ينطبق ما يلي على أي درس له موعد محجوز (الدروس الخاصة والحصص الجماعية المباشرة):"],
        box: { title: "كيف يعمل إلغاء الدروس", items: [
          { b: "إشعار قبل أكثر من 24 ساعة.", t: "يمكنك تغيير الموعد أو الإلغاء مجانًا، ويبقى الدرس في باقتك لاستخدامه في وقت آخر." },
          { b: "إشعار قبل أقل من 24 ساعة، أو عدم الحضور، دون سبب مقبول.", t: "يُحتسب الدرس على أنه مكتمل ويُخصم من باقتك. ويشمل السبب المقبول أمورًا مثل المرض أو حالة طارئة عائلية أو أي ظرف حقيقي آخر خارج عن إرادتك، يُقيَّم بشكل معقول وبحسن نية." },
          { b: "حد الاستخدام العادل.", t: "يمكن لكل طالب الاستفادة من هذا الاستثناء للإلغاء المتأخر حتى مرتين (2) خلال الباقة الواحدة أو فترة العضوية الواحدة." },
          { b: "بعد المرة الثانية.", t: "إذا تكرر الأمر للمرة الثالثة، سنتوقف قليلًا ونجري معك محادثة ودية لنفهم ما يحدث ونجد حلًا مناسبًا، سواء بتعديل مواعيدك أو خطتك أو الدعم الذي نقدّمه لك. هدفنا دائمًا هو مساعدتك على مواصلة التعلم، لا معاقبتك." },
        ] },
        after: ["كلما أمكن، يرجى إعلامنا في أقرب وقت ممكن حتى نتمكن من عرض موعدك على طالب آخر ومساعدتك في إيجاد وقت أنسب. وإذا احتجت إلى الإلغاء، أبلغنا عبر قناة التواصل المعتادة (مثل واتساب أو البريد الإلكتروني)."] },
      { h: "5. الدرس التجريبي المجاني",
        p: ["يمكن للطلاب الجدد حجز درس تجريبي مجاني واحد لنتعرّف على بعضنا ونخطط لمسار التعلم المناسب لك. الدرس التجريبي مجاني ولا يترتب عليه أي التزام بالاستمرار. ويُقدَّم مرة واحدة لكل طالب، وقد نحدّ من تكرار حجز الدروس التجريبية."] },
      { h: "6. العضوية",
        bullets: [
          "تُحتسب رسوم العضوية شهريًا وتتجدد تلقائيًا حتى تقوم بإلغائها.",
          "يمكنك إلغاء عضويتك في أي وقت. وعند الإلغاء، يستمر وصولك حتى نهاية الفترة التي دفعت مقابلها، ولن تُحتسب عليك أي رسوم بعد ذلك.",
          "تنطبق الأسعار التعريفية أو الترويجية (مثل خصم على الشهر الأول) فقط كما هو موضّح وقت التسجيل، وبعد ذلك تُطبَّق الأسعار العادية.",
          "تمنحك العضوية الوصول إلى منطقة الأعضاء ومحتواها كما هو متاح من وقت لآخر. نضيف مواد جديدة بانتظام، لكن المحتوى المتاح تحديدًا قد يتغير.",
        ] },
      { h: "7. استرداد المبالغ",
        p: ["نظرًا لأن دروسنا وموادنا ومحتوى الأعضاء تُقدَّم رقميًا، ولأن مواعيد الدروس محجوزة لك خصيصًا، فإن الرسوم بشكل عام غير قابلة للاسترداد إلا في الحالات التي يفرض فيها القانون الاسترداد. ولا تُسترد رسوم الدروس التي أُخذت بالفعل أو احتُسبت على أنها مكتملة (بما في ذلك وفق البند 4). وإذا كنت ترى أن هناك ظروفًا استثنائية، يرجى التواصل معنا، وسنراجع حالتك دائمًا بعدل وحسن نية."] },
      { h: "8. سلوك الطالب والمجتمع",
        p: ["MundoLingu مجتمع تعليمي ودود ومحترم. وعند مشاركتك في الدروس أو الحصص المباشرة أو أي مساحة تابعة لـ MundoLingu، فإنك توافق على:"],
        bullets: [
          "معاملة المعلمين وزملائك الطلاب بلطف واحترام.",
          "عدم تسجيل الدروس أو الحصص المباشرة أو مشاركات الطلاب الآخرين أو مشاركتها أو إعادة نشرها دون إذن.",
          "عدم استخدام خدمات MundoLingu لأي غرض غير قانوني أو ضار أو مسيء.",
        ],
        after: ["يجوز لنا إيقاف أو إنهاء وصول أي شخص يتصرف بشكل مسيء أو يخالف هذه الشروط بشكل متكرر، ودون استرداد الرسوم حيثما كان ذلك مناسبًا."] },
      { h: "9. المواد التعليمية والملكية الفكرية",
        p: ["جميع دروس MundoLingu وكتب التمارين ومقاطع الفيديو والرسومات وغيرها من المواد مملوكة لـ MundoLingu (أو مستخدمة بإذن) ومحمية بموجب قوانين الملكية الفكرية. وهي مقدّمة لتعلمك الشخصي فقط. يمكنك تنزيل المواد واستخدامها في دراستك، لكن لا يجوز لك نسخها أو إعادة بيعها أو توزيعها أو مشاركتها علنًا دون إذن كتابي منا."] },
      { h: "10. الخصوصية وبياناتك",
        p: ["نجمع المعلومات الشخصية ونستخدمها (مثل اسمك وبريدك الإلكتروني ورقم هاتفك وتفضيلاتك التعليمية) فقط لتقديم خدماتنا وتحسينها، وتنظيم دروسك، والتواصل معك. نحن لا نبيع بياناتك الشخصية. وإذا رغبت في معرفة المعلومات التي نحتفظ بها، أو طلب تحديثها أو حذفها، يرجى التواصل معنا عبر البيانات الواردة في نهاية هذه الشروط."] },
      { h: "11. توفّر الخدمة",
        p: ["نعمل بجد لضمان سير الدروس ومنطقة الأعضاء بسلاسة، لكن الخدمات عبر الإنترنت قد تتأثر أحيانًا بمشكلات تقنية أو بمنصات خارجية أو بأحداث خارجة عن سيطرتنا. وإذا تعذّر عقد درس بسبب مشكلة من جانبنا، فسنعيد جدولته أو نعيده إلى باقتك."] },
      { h: "12. التغييرات على هذه الشروط",
        p: ["قد نحدّث هذه الشروط من وقت لآخر، مثلًا لتعكس ميزات جديدة أو متطلبات قانونية. وستُنشر أحدث نسخة دائمًا على موقعنا الإلكتروني مع تاريخ التحديث. واستمرارك في استخدام خدماتنا بعد أي تغيير يعني موافقتك على الشروط المحدّثة."] },
      { h: "13. المسؤولية",
        p: ["تقدّم MundoLingu تعليمًا ودعمًا في اللغات لمساعدتك على التعلم، لكننا لا نستطيع ضمان أي نتيجة محددة أو درجة اختبار أو مستوى طلاقة، لأن التقدم يعتمد على عوامل كثيرة منها تدرّبك الشخصي. وإلى أقصى حد يسمح به القانون، لا تتحمل MundoLingu المسؤولية عن الخسائر غير المباشرة أو غير المتوقعة الناشئة عن استخدام خدماتنا. ولا يوجد في هذه الشروط ما يحدّ من أي حقوق لا يجوز استبعادها بموجب القانون."] },
      { h: "14. القانون المعمول به",
        p: ["تخضع هذه الشروط لقوانين دولة الإمارات العربية المتحدة (دبي)، دون المساس بأي حقوق إلزامية لحماية المستهلك قد تكون لك في بلد إقامتك."] },
      { h: "15. تواصل معنا",
        p: ["إذا كانت لديك أي أسئلة حول هذه الشروط أو دروسك، يسعدنا مساعدتك:"],
        bullets: ["البريد الإلكتروني: mundolingu@gmail.com", "واتساب: ‎+971 50 429 6090", "الموقع الإلكتروني: www.mundolingu.com", "إنستغرام: ‎@mundolingu"] },
    ],
    thanks: "شكرًا لتعلّمك مع MundoLingu. نتطلع إلى مساعدتك في تحقيق أهدافك اللغوية.",
  },
};
